name:                fo-bottom-up
version:             0.1.0.0
github:              "paulkrog/fo-bottom-up"
license:             BSD3
author:              "Paul Krogmeier"
maintainer:          "paulmk2@illinois.edu"
copyright:           "2022 Paul Krogmeier"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/foil-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - hashable
  - unordered-containers
  - containers
  - aeson
  - text
  - bytestring
  - directory
  - regex-tdfa
  - filepath
  - random
  - parsec
  - mtl
  - parallel
  - filepath

executables:
  fo-bottom-up-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    dependencies:
    - fo-bottom-up
    - parallel
    - async
    - directory
    - hashable
    - filepath

tests:
  fo-bottom-up-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fo-bottom-up
